---
name: "MQTT TLS bi-directional Cloud Sync"
version: 1.0.0
slug: "mqtt-cloud-synchronizer"
description: Synchronization between HAOS Entities and MQTT Cloud Broker
url: https://github.com/jean-luc1203/HomeAssistant-MQTT-Cloud-2way-Synchronizer
ingress: false
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2025.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
privileged:
  - NET_ADMIN
  - SYS_RAWIO
ports:
  "1892/tcp": 1892
ports_description:
  "1892/tcp": Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl

options:
  # MQTT Configuration
  mqttadresse_port: "core-mosquitto.local.hass.io:1883"
  mqttuser: "username"
  mqttpass: "password"

  # Cloud MQTT Broker Configuration
  cloud_broker_adress_port: "bca204074b374abvcdefbae5b858.s1.eu.hivemq.cloud:8883"
  cloud_broker_user: "username"
  cloud_broker_pass: "password"
  cloud_HA_long_term_access_tokens: "abcdefghijklmnopqrstuvwxyz123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  haos_url: "http://homeassistant:8123"

schema:
  # MQTT Configuration
  mqttadresse_port: str?
  mqttuser: str?
  mqttpass: password?

  # Cloud MQTT Broker Configuration
  cloud_broker: bool?
  cloud_broker_adress_port: str?
  cloud_broker_user: str?
  cloud_broker_pass: password?
  cloud_HA_long_term_access_tokens: str?
  haos_url: str?
